name: Silver Data Pipeline

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches: [ "main" ]

env:
  raw_source_folder: "data/raw/seviri" # Local folder containing raw data
  source_folder: "data/processed/seviri" # Local folder containing silver data
  target_container: "silver" # ADLS container name for silver data

jobs:
  silver-job:
    runs-on: ubuntu-latest
    environment:
      name: "development"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          pip install azure-storage-file-datalake
          pip install -e .
          # Add requirements for your generation script here (e.g., zarr, numpy)
          # pip install zarr numpy 

      - name: Generate Silver Data
        # Replace this with the command to run your script
        run: python src/data/create_silver_data.py  --input ${{ env.raw_source_folder }} --output ${{ env.source_folder }}

      - name: Upload to Silver Container
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          # Usage: python upload_zarr.py <source_folder> <container_name>
          python upload_zarr.py ${{ env.source_folder }} ${{ env.target_container }}