name: Upload data to ADLS Gen2 (Silver & Gold)

on:
  push:
    branches: [ main ]
  workflow_dispatch:


env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID:    ${{ secrets.AZURE_CLIENT_ID }}
  STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}

jobs:
  upload:
    runs-on: ubuntu-latest
    environment:
      name: "development"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (AAD)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install AzCopy
        run: |
          wget https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz
          tar -xf azcopy.tar.gz
          sudo mv azcopy_linux_amd64_*/azcopy /usr/local/bin/
          azcopy --version

      - name: Upload SILVER data
        run: |
          SRC="data/silver"
          DEST="https://${STORAGE_ACCOUNT}.dfs.core.windows.net/silver"

          azcopy copy "$SRC" "$DEST" \
            --recursive \
            --overwrite=true \
            --from-to=LocalBlob \
            --log-level=INFO

      - name: Upload GOLD data
        run: |
          SRC="data/gold"
          DEST="https://${STORAGE_ACCOUNT}.dfs.core.windows.net/gold"

          azcopy copy "$SRC" "$DEST" \
            --recursive \
            --overwrite=true \
            --from-to=LocalBlob \
            --log-level=INFO
